export const TOGGLE_CANDIDATE_MENU = "TOGGLE_CANDIDATE_MENU";
export const TOGGLE_USER_MENU = "TOGGLE_USER_MENU";
export const TOGGLE_CLASS_MENU = "TOGGLE_CLASS_MENU";
export const TOGGLE_VOLUNTEER_MENU = "TOGGLE_VOLUNTEER_MENU";
export const OPEN_CLASS_MENU = "OPEN_CLASS_MENU";

//user

export const ADD_USER = "ADD_USER";

//auth
export const LOGIN = "LOGIN";
export const LOGGOUT = "LOGGOUT";
export const FETCH_LOGIN = "FETCH_LOGIN";
export const ON_FETCH_USER_FAIL = "ON_FETCH_USER_FAIL";

//selects
export const SET_KINSHIP = "SET_KINSHIP";
export const LOADING_OPTIONS = "LOADING_OPTIONS";
export const ON_FETCH_KINSHIP_FAIL = "ON_FETCH_KINSHIP_FAIL";

export const SET_CS = "SET_CS";
export const LOADING_OPTIONS_CS = "LOADING_OPTIONS_CS";
export const ON_FETCH_CS_FAIL = "ON_FETCH_CS_FAIL";

export const SET_RACE = "SET_RACE";
export const LOADING_OPTIONS_RACE = "LOADING_OPTIONS_RACE";
export const ON_FETCH_RACE_FAIL = "ON_FETCH_RACE_FAIL";

export const SET_WS = "SET_WS";
export const LOADING_OPTIONS_WS = "LOADING_OPTIONS_WS";
export const ON_FETCH_WS_FAIL = "ON_FETCH_WS_FAIL";

//search

export const SET_SEARCH = "SET_SEARCH";
export const LOADING_SEARCH = "LOADING_SEARCH";
export const ON_FETCH_SEARCH_FAIL = "ON_FETCH_SEARCH_FAIL";

//address

export const SET_ADDRESS = "SET_ADDRESS";
export const LOADING_ADDRESS = "LOADING_ADDRESS";
export const ON_FETCH_ADDRESS_FAIL = "ON_FETCH_ADDRESS_FAIL";


//search city

export const SET_SEARCH_CITY = "SET_SEARCH_CITY";
export const LOADING_SEARCH_CITY = "LOADING_SEARCH_CITY";
export const ON_FETCH_SEARCH_CITY_FAIL = "ON_FETCH_SEARCH_CITY_FAIL";
