export const TOGGLE_CANDIDATE_MENU = 'TOGGLE_CANDIDATE_MENU'
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU'
export const TOGGLE_CLASS_MENU = 'TOGGLE_CLASS_MENU'
export const OPEN_CLASS_MENU = 'OPEN_CLASS_MENU'